import { PrismaClient, QuizDifficulty } from '@prisma/client';

const prisma = new PrismaClient();

const questions = [
  {
    prompt: "Wie heißt die Hauptstadt Deutschlands?",
    choices: JSON.stringify(["Berlin", "München", "Hamburg", "Bonn"]),
    answerIndex: 0,
    fact: "Berlin ist seit 1990 wieder Hauptstadt des vereinten Deutschlands.",
    tags: JSON.stringify(["Deutschland", "Geografie"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farben hat die deutsche Flagge?",
    choices: JSON.stringify(["Schwarz-Rot-Gold", "Schwarz-Gold-Rot", "Rot-Schwarz-Gold"]),
    answerIndex: 0,
    fact: "Die Farben sind in horizontalen Streifen angeordnet.",
    tags: JSON.stringify(["Deutschland", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welcher Fluss fließt durch Köln?",
    choices: JSON.stringify(["Rhein", "Elbe", "Weser", "Main"]),
    answerIndex: 0,
    fact: "Der Rhein ist der längste Fluss, der durch Deutschland fließt.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wofür ist München weltbekannt im Herbst?",
    choices: JSON.stringify(["Oktoberfest", "Karneval", "Documenta"]),
    answerIndex: 0,
    fact: "Das Oktoberfest ist das größte Volksfest der Welt.",
    tags: JSON.stringify(["Kultur", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wann ist der Tag der Deutschen Einheit?",
    choices: JSON.stringify(["3. Oktober", "9. November", "1. Mai", "17. Juni"]),
    answerIndex: 0,
    fact: "Seit 1990 ist der 3. Oktober gesetzlicher Feiertag.",
    tags: JSON.stringify(["Geschichte", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Bundesländer hat Deutschland?",
    choices: JSON.stringify(["16", "14", "18", "12"]),
    answerIndex: 0,
    fact: "Davon sind 3 Stadtstaaten: Berlin, Hamburg und Bremen.",
    tags: JSON.stringify(["Politik", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wo steht das Brandenburger Tor?",
    choices: JSON.stringify(["Berlin", "Potsdam", "Leipzig"]),
    answerIndex: 0,
    fact: "Es steht am Pariser Platz im Zentrum Berlins.",
    tags: JSON.stringify(["Sehenswürdigkeiten", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wer komponierte die 9. Sinfonie mit der 'Ode an die Freude'?",
    choices: JSON.stringify(["Ludwig van Beethoven", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart"]),
    answerIndex: 0,
    fact: "Beethoven wurde 1770 in Bonn geboren.",
    tags: JSON.stringify(["Kultur", "Musik"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Meer liegt an der deutschen Nordküste?",
    choices: JSON.stringify(["Nordsee", "Ostsee", "Ärmelkanal"]),
    answerIndex: 0,
    fact: "Deutschland hat sowohl Nord- als auch Ostseeküste.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Währung wurde 2002 als Bargeld eingeführt?",
    choices: JSON.stringify(["Euro", "D-Mark", "Schilling"]),
    answerIndex: 0,
    fact: "Der Euro ist seit 1999 Buchgeld, seit 2002 Bargeld.",
    tags: JSON.stringify(["Zeitgeschichte", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "In welcher Stadt steht der Kölner Dom?",
    choices: JSON.stringify(["Köln", "Düsseldorf", "Bonn", "Aachen"]),
    answerIndex: 0,
    fact: "Der Kölner Dom ist eine der meistbesuchten Sehenswürdigkeiten Deutschlands.",
    tags: JSON.stringify(["Sehenswürdigkeiten", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Bundesland ist das größte nach Fläche?",
    choices: JSON.stringify(["Bayern", "Niedersachsen", "Baden-Württemberg", "Nordrhein-Westfalen"]),
    answerIndex: 0,
    fact: "Bayern hat eine Fläche von etwa 70.550 km².",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wie heißt der höchste Berg Deutschlands?",
    choices: JSON.stringify(["Zugspitze", "Watzmann", "Feldberg", "Brocken"]),
    answerIndex: 0,
    fact: "Die Zugspitze ist 2.962 Meter hoch.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Stadt wird auch 'Elbflorenz' genannt?",
    choices: JSON.stringify(["Dresden", "Leipzig", "Magdeburg", "Erfurt"]),
    answerIndex: 0,
    fact: "Dresden trägt diesen Beinamen wegen seiner Kunstschätze.",
    tags: JSON.stringify(["Kultur", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wann fiel die Berliner Mauer?",
    choices: JSON.stringify(["9. November 1989", "3. Oktober 1990", "13. August 1961", "1. Mai 1989"]),
    answerIndex: 0,
    fact: "Die Mauer stand 28 Jahre lang.",
    tags: JSON.stringify(["Geschichte", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier ist das Wappentier Deutschlands?",
    choices: JSON.stringify(["Adler", "Löwe", "Bär", "Hirsch"]),
    answerIndex: 0,
    fact: "Der Bundesadler ist seit 1950 das Wappentier.",
    tags: JSON.stringify(["Allgemeinwissen", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "In welcher Stadt findet die Documenta statt?",
    choices: JSON.stringify(["Kassel", "Frankfurt", "München", "Hamburg"]),
    answerIndex: 0,
    fact: "Die Documenta ist eine der wichtigsten Ausstellungen zeitgenössischer Kunst.",
    tags: JSON.stringify(["Kultur", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welcher Fluss fließt durch Hamburg?",
    choices: JSON.stringify(["Elbe", "Rhein", "Weser", "Oder"]),
    answerIndex: 0,
    fact: "Hamburg ist die größte Hafenstadt Deutschlands.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt der deutsche Bundespräsident? (Stand 2024)",
    choices: JSON.stringify(["Frank-Walter Steinmeier", "Joachim Gauck", "Christian Wulff", "Horst Köhler"]),
    answerIndex: 0,
    fact: "Steinmeier ist seit 2017 im Amt.",
    tags: JSON.stringify(["Politik", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Fest wird in Köln besonders groß gefeiert?",
    choices: JSON.stringify(["Karneval", "Oktoberfest", "Weihnachtsmarkt"]),
    answerIndex: 0,
    fact: "Der Kölner Karneval ist einer der größten in Deutschland.",
    tags: JSON.stringify(["Kultur", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farbe hat ein deutsches Taxi traditionell?",
    choices: JSON.stringify(["Beige/Elfenbein", "Gelb", "Schwarz", "Weiß"]),
    answerIndex: 0,
    fact: "Seit den 1970er Jahren sind deutsche Taxis meist beige.",
    tags: JSON.stringify(["Allgemeinwissen", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wie viele Nachbarländer hat Deutschland?",
    choices: JSON.stringify(["9", "7", "8", "10"]),
    answerIndex: 0,
    fact: "Deutschland grenzt an Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Märchen stammt NICHT von den Brüdern Grimm?",
    choices: JSON.stringify(["Die kleine Meerjungfrau", "Rotkäppchen", "Hänsel und Gretel", "Schneewittchen"]),
    answerIndex: 0,
    fact: "Die kleine Meerjungfrau ist von Hans Christian Andersen.",
    tags: JSON.stringify(["Kultur", "Literatur"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "In welcher Stadt befindet sich die Frauenkirche mit der berühmten Kuppel?",
    choices: JSON.stringify(["Dresden", "München", "Nürnberg", "Würzburg"]),
    answerIndex: 0,
    fact: "Die Dresdner Frauenkirche wurde nach der Zerstörung im 2. Weltkrieg wieder aufgebaut.",
    tags: JSON.stringify(["Sehenswürdigkeiten", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Getränk wird traditionell auf dem Oktoberfest ausgeschenkt?",
    choices: JSON.stringify(["Bier", "Wein", "Apfelwein", "Schnaps"]),
    answerIndex: 0,
    fact: "Nur Münchner Brauereien dürfen auf dem Oktoberfest ausschenken.",
    tags: JSON.stringify(["Kultur", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt der berühmte Schwarzwald-Kuchen?",
    choices: JSON.stringify(["Schwarzwälder Kirschtorte", "Baumkuchen", "Apfelstrudel", "Käsekuchen"]),
    answerIndex: 0,
    fact: "Die Schwarzwälder Kirschtorte enthält Kirschwasser.",
    tags: JSON.stringify(["Kultur", "Kulinarik"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Stadt ist bekannt für ihre Automobilindustrie und Mercedes-Benz?",
    choices: JSON.stringify(["Stuttgart", "München", "Wolfsburg", "Ingolstadt"]),
    answerIndex: 0,
    fact: "Stuttgart ist die Hauptstadt von Baden-Württemberg.",
    tags: JSON.stringify(["Wirtschaft", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wie heißt das deutsche Grundgesetz auf Englisch?",
    choices: JSON.stringify(["Basic Law", "Constitution", "Federal Law", "Main Law"]),
    answerIndex: 0,
    fact: "Das Grundgesetz trat 1949 in Kraft.",
    tags: JSON.stringify(["Politik", "Deutschland"]),
    difficulty: QuizDifficulty.HARD,
  },
  {
    prompt: "Welcher deutsche Dichter schrieb 'Faust'?",
    choices: JSON.stringify(["Johann Wolfgang von Goethe", "Friedrich Schiller", "Heinrich Heine", "Bertolt Brecht"]),
    answerIndex: 0,
    fact: "Goethe lebte von 1749 bis 1832.",
    tags: JSON.stringify(["Kultur", "Literatur"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Bundesland hat die meisten Einwohner?",
    choices: JSON.stringify(["Nordrhein-Westfalen", "Bayern", "Baden-Württemberg", "Niedersachsen"]),
    answerIndex: 0,
    fact: "NRW hat etwa 18 Millionen Einwohner.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welche Stadt ist die Hauptstadt von Bayern?",
    choices: JSON.stringify(["München", "Nürnberg", "Augsburg", "Regensburg"]),
    answerIndex: 0,
    fact: "München ist mit über 1,5 Millionen Einwohnern die drittgrößte Stadt Deutschlands.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt der längste Fluss Deutschlands?",
    choices: JSON.stringify(["Rhein", "Donau", "Elbe", "Weser"]),
    answerIndex: 0,
    fact: "Der Rhein ist 1.233 km lang, davon 865 km in Deutschland.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "In welchem Jahr wurde die Bundesrepublik Deutschland gegründet?",
    choices: JSON.stringify(["1949", "1945", "1950", "1948"]),
    answerIndex: 0,
    fact: "Das Grundgesetz trat am 23. Mai 1949 in Kraft.",
    tags: JSON.stringify(["Geschichte", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Bundesland ist ein Stadtstaat?",
    choices: JSON.stringify(["Hamburg", "München", "Köln", "Frankfurt"]),
    answerIndex: 0,
    fact: "Die drei Stadtstaaten sind Berlin, Hamburg und Bremen.",
    tags: JSON.stringify(["Politik", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Sterne hat die Europaflagge?",
    choices: JSON.stringify(["12", "15", "27", "28"]),
    answerIndex: 0,
    fact: "Die 12 Sterne stehen für Einheit, Solidarität und Harmonie.",
    tags: JSON.stringify(["Europa", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welcher deutsche Erfinder entwickelte das Auto?",
    choices: JSON.stringify(["Carl Benz", "Rudolf Diesel", "Gottlieb Daimler", "Ferdinand Porsche"]),
    answerIndex: 0,
    fact: "Carl Benz baute 1885 das erste Automobil mit Verbrennungsmotor.",
    tags: JSON.stringify(["Geschichte", "Technik"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welche Farbe hat ein Stopp-Schild in Deutschland?",
    choices: JSON.stringify(["Rot", "Gelb", "Blau", "Grün"]),
    answerIndex: 0,
    fact: "Das achteckige rote Stopp-Schild ist weltweit einheitlich.",
    tags: JSON.stringify(["Verkehr", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die deutsche Nationalhymne?",
    choices: JSON.stringify(["Das Lied der Deutschen", "Deutschland über alles", "Einigkeit und Recht und Freiheit", "Die Wacht am Rhein"]),
    answerIndex: 0,
    fact: "Nur die dritte Strophe wird als Nationalhymne gesungen.",
    tags: JSON.stringify(["Kultur", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Tier ist auf dem Wappen von Berlin?",
    choices: JSON.stringify(["Bär", "Adler", "Löwe", "Pferd"]),
    answerIndex: 0,
    fact: "Der Berliner Bär ist seit dem 13. Jahrhundert das Wappentier.",
    tags: JSON.stringify(["Kultur", "Deutschland"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Minuten hat eine Halbzeit im Fußball?",
    choices: JSON.stringify(["45", "40", "50", "60"]),
    answerIndex: 0,
    fact: "Plus Nachspielzeit, die der Schiedsrichter festlegt.",
    tags: JSON.stringify(["Sport", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Stadt wird 'Venedig des Nordens' genannt?",
    choices: JSON.stringify(["Hamburg", "Amsterdam", "Stockholm", "Kopenhagen"]),
    answerIndex: 0,
    fact: "Hamburg hat mehr Brücken als Venedig und Amsterdam zusammen.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wer schrieb 'Die Leiden des jungen Werther'?",
    choices: JSON.stringify(["Johann Wolfgang von Goethe", "Friedrich Schiller", "Heinrich Heine", "Thomas Mann"]),
    answerIndex: 0,
    fact: "Das Buch erschien 1774 und machte Goethe berühmt.",
    tags: JSON.stringify(["Literatur", "Kultur"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Fest wird am 6. Dezember gefeiert?",
    choices: JSON.stringify(["Nikolaus", "Weihnachten", "Advent", "Heiligabend"]),
    answerIndex: 0,
    fact: "Der Nikolaustag erinnert an den Bischof Nikolaus von Myra.",
    tags: JSON.stringify(["Kultur", "Tradition"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Tasten hat ein Klavier normalerweise?",
    choices: JSON.stringify(["88", "76", "100", "64"]),
    answerIndex: 0,
    fact: "52 weiße und 36 schwarze Tasten.",
    tags: JSON.stringify(["Musik", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welcher Planet ist der Sonne am nächsten?",
    choices: JSON.stringify(["Merkur", "Venus", "Erde", "Mars"]),
    answerIndex: 0,
    fact: "Merkur ist nur etwa 58 Millionen km von der Sonne entfernt.",
    tags: JSON.stringify(["Wissenschaft", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt der höchste Berg der Alpen?",
    choices: JSON.stringify(["Mont Blanc", "Matterhorn", "Zugspitze", "Großglockner"]),
    answerIndex: 0,
    fact: "Der Mont Blanc ist 4.810 Meter hoch.",
    tags: JSON.stringify(["Geografie", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Organ pumpt das Blut durch den Körper?",
    choices: JSON.stringify(["Herz", "Lunge", "Leber", "Niere"]),
    answerIndex: 0,
    fact: "Das Herz schlägt etwa 100.000 Mal pro Tag.",
    tags: JSON.stringify(["Gesundheit", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Bundesländer grenzen an die Nordsee?",
    choices: JSON.stringify(["3", "2", "4", "5"]),
    answerIndex: 0,
    fact: "Niedersachsen, Hamburg und Schleswig-Holstein.",
    tags: JSON.stringify(["Geografie", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welche Farbe entsteht, wenn man Gelb und Blau mischt?",
    choices: JSON.stringify(["Grün", "Orange", "Lila", "Braun"]),
    answerIndex: 0,
    fact: "Grün ist eine Sekundärfarbe.",
    tags: JSON.stringify(["Kunst", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "In welcher Stadt steht das Schloss Neuschwanstein?",
    choices: JSON.stringify(["Füssen", "München", "Nürnberg", "Augsburg"]),
    answerIndex: 0,
    fact: "Das Schloss diente als Vorlage für das Disney-Schloss.",
    tags: JSON.stringify(["Sehenswürdigkeiten", "Deutschland"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wie viele Spieler hat eine Fußballmannschaft auf dem Feld?",
    choices: JSON.stringify(["11", "10", "12", "9"]),
    answerIndex: 0,
    fact: "Plus Auswechselspieler auf der Bank.",
    tags: JSON.stringify(["Sport", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welcher Monat hat immer 28 Tage?",
    choices: JSON.stringify(["Alle", "Februar", "Januar", "Dezember"]),
    answerIndex: 0,
    fact: "Jeder Monat hat mindestens 28 Tage!",
    tags: JSON.stringify(["Allgemeinwissen", "Rätsel"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Frankreich?",
    choices: JSON.stringify(["Paris", "Lyon", "Marseille", "Nizza"]),
    answerIndex: 0,
    fact: "Paris wird auch 'Stadt der Liebe' genannt.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier legt Eier und kann fliegen?",
    choices: JSON.stringify(["Vogel", "Fledermaus", "Schmetterling", "Biene"]),
    answerIndex: 0,
    fact: "Fast alle Vögel können fliegen, außer z.B. Pinguine und Strauße.",
    tags: JSON.stringify(["Natur", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Kontinente gibt es auf der Erde?",
    choices: JSON.stringify(["7", "5", "6", "8"]),
    answerIndex: 0,
    fact: "Afrika, Antarktika, Asien, Australien, Europa, Nordamerika, Südamerika.",
    tags: JSON.stringify(["Geografie", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Jahreszeit kommt nach dem Sommer?",
    choices: JSON.stringify(["Herbst", "Winter", "Frühling", "Spätsommer"]),
    answerIndex: 0,
    fact: "Der Herbst beginnt am 22. oder 23. September.",
    tags: JSON.stringify(["Natur", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Beine hat eine Spinne?",
    choices: JSON.stringify(["8", "6", "10", "12"]),
    answerIndex: 0,
    fact: "Spinnen gehören zu den Spinnentieren, nicht zu den Insekten.",
    tags: JSON.stringify(["Natur", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Getränk wird aus Kaffeebohnen gemacht?",
    choices: JSON.stringify(["Kaffee", "Tee", "Kakao", "Cola"]),
    answerIndex: 0,
    fact: "Kaffee ist nach Wasser das meistgetrunkene Getränk weltweit.",
    tags: JSON.stringify(["Kulinarik", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt der größte Ozean der Welt?",
    choices: JSON.stringify(["Pazifik", "Atlantik", "Indischer Ozean", "Arktischer Ozean"]),
    answerIndex: 0,
    fact: "Der Pazifik bedeckt etwa ein Drittel der Erdoberfläche.",
    tags: JSON.stringify(["Geografie", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Fest feiern wir am 24. Dezember?",
    choices: JSON.stringify(["Heiligabend", "Weihnachten", "Silvester", "Neujahr"]),
    answerIndex: 0,
    fact: "In Deutschland werden die Geschenke traditionell am 24. Dezember ausgepackt.",
    tags: JSON.stringify(["Kultur", "Tradition"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Zähne hat ein erwachsener Mensch normalerweise?",
    choices: JSON.stringify(["32", "28", "30", "36"]),
    answerIndex: 0,
    fact: "Inklusive der vier Weisheitszähne.",
    tags: JSON.stringify(["Gesundheit", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Tier ist das schnellste Landtier?",
    choices: JSON.stringify(["Gepard", "Löwe", "Pferd", "Antilope"]),
    answerIndex: 0,
    fact: "Ein Gepard kann bis zu 120 km/h schnell laufen.",
    tags: JSON.stringify(["Natur", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "In welcher Stadt steht der Eiffelturm?",
    choices: JSON.stringify(["Paris", "London", "Rom", "Berlin"]),
    answerIndex: 0,
    fact: "Der Eiffelturm ist 330 Meter hoch.",
    tags: JSON.stringify(["Geografie", "Sehenswürdigkeiten"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Italien?",
    choices: JSON.stringify(["Rom", "Mailand", "Venedig", "Florenz"]),
    answerIndex: 0,
    fact: "Rom wird auch 'Die Ewige Stadt' genannt.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Instrument hat 88 Tasten?",
    choices: JSON.stringify(["Klavier", "Orgel", "Keyboard", "Akkordeon"]),
    answerIndex: 0,
    fact: "Ein Konzertflügel ist die größte Form des Klaviers.",
    tags: JSON.stringify(["Musik", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Stunden hat ein Tag?",
    choices: JSON.stringify(["24", "12", "48", "36"]),
    answerIndex: 0,
    fact: "Die Erde dreht sich in 24 Stunden einmal um ihre Achse.",
    tags: JSON.stringify(["Zeit", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farbe hat eine Zitrone?",
    choices: JSON.stringify(["Gelb", "Grün", "Orange", "Rot"]),
    answerIndex: 0,
    fact: "Zitronen sind reich an Vitamin C.",
    tags: JSON.stringify(["Natur", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie nennt man den Arzt für Zähne?",
    choices: JSON.stringify(["Zahnarzt", "Augenarzt", "Hautarzt", "Kinderarzt"]),
    answerIndex: 0,
    fact: "Regelmäßige Zahnarztbesuche sind wichtig für die Zahngesundheit.",
    tags: JSON.stringify(["Gesundheit", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier gibt uns Milch?",
    choices: JSON.stringify(["Kuh", "Pferd", "Schwein", "Huhn"]),
    answerIndex: 0,
    fact: "Eine Kuh gibt durchschnittlich 20-25 Liter Milch pro Tag.",
    tags: JSON.stringify(["Natur", "Landwirtschaft"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Ecken hat ein Dreieck?",
    choices: JSON.stringify(["3", "4", "5", "6"]),
    answerIndex: 0,
    fact: "Ein Dreieck ist die einfachste geometrische Form.",
    tags: JSON.stringify(["Mathematik", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welcher Wochentag kommt nach Montag?",
    choices: JSON.stringify(["Dienstag", "Mittwoch", "Donnerstag", "Sonntag"]),
    answerIndex: 0,
    fact: "Die Woche hat sieben Tage.",
    tags: JSON.stringify(["Zeit", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier bellt?",
    choices: JSON.stringify(["Hund", "Katze", "Vogel", "Pferd"]),
    answerIndex: 0,
    fact: "Hunde bellen zur Kommunikation.",
    tags: JSON.stringify(["Tiere", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Finger hat eine Hand?",
    choices: JSON.stringify(["5", "4", "6", "10"]),
    answerIndex: 0,
    fact: "Inklusive des Daumens.",
    tags: JSON.stringify(["Körper", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farbe hat der Himmel an einem klaren Tag?",
    choices: JSON.stringify(["Blau", "Grün", "Rot", "Gelb"]),
    answerIndex: 0,
    fact: "Das Blau entsteht durch die Streuung des Sonnenlichts.",
    tags: JSON.stringify(["Natur", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Spanien?",
    choices: JSON.stringify(["Madrid", "Barcelona", "Sevilla", "Valencia"]),
    answerIndex: 0,
    fact: "Madrid liegt im Zentrum Spaniens.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier gibt uns Wolle?",
    choices: JSON.stringify(["Schaf", "Ziege", "Kuh", "Pferd"]),
    answerIndex: 0,
    fact: "Schafwolle wird für Kleidung verwendet.",
    tags: JSON.stringify(["Tiere", "Landwirtschaft"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Räder hat ein Fahrrad?",
    choices: JSON.stringify(["2", "3", "4", "1"]),
    answerIndex: 0,
    fact: "Ein Dreirad hat 3 Räder.",
    tags: JSON.stringify(["Verkehr", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Jahreszeit kommt nach dem Winter?",
    choices: JSON.stringify(["Frühling", "Sommer", "Herbst", "Winter"]),
    answerIndex: 0,
    fact: "Im Frühling beginnen die Pflanzen zu blühen.",
    tags: JSON.stringify(["Natur", "Jahreszeiten"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Österreich?",
    choices: JSON.stringify(["Wien", "Salzburg", "Innsbruck", "Graz"]),
    answerIndex: 0,
    fact: "Wien ist bekannt für klassische Musik.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier miaut?",
    choices: JSON.stringify(["Katze", "Hund", "Vogel", "Maus"]),
    answerIndex: 0,
    fact: "Katzen miauen zur Kommunikation mit Menschen.",
    tags: JSON.stringify(["Tiere", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Monate hat ein Jahr?",
    choices: JSON.stringify(["12", "10", "11", "13"]),
    answerIndex: 0,
    fact: "Jeder Monat hat einen eigenen Namen.",
    tags: JSON.stringify(["Zeit", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farbe hat eine Tomate?",
    choices: JSON.stringify(["Rot", "Grün", "Gelb", "Blau"]),
    answerIndex: 0,
    fact: "Unreife Tomaten sind grün.",
    tags: JSON.stringify(["Natur", "Lebensmittel"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt der größte Kontinent?",
    choices: JSON.stringify(["Asien", "Afrika", "Europa", "Amerika"]),
    answerIndex: 0,
    fact: "Asien hat über 4,5 Milliarden Einwohner.",
    tags: JSON.stringify(["Geografie", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Tier legt die größten Eier?",
    choices: JSON.stringify(["Strauß", "Huhn", "Ente", "Gans"]),
    answerIndex: 0,
    fact: "Ein Straußenei wiegt etwa 1,5 kg.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wie viele Bundesländer hat Österreich?",
    choices: JSON.stringify(["9", "7", "10", "8"]),
    answerIndex: 0,
    fact: "Wien ist sowohl Stadt als auch Bundesland.",
    tags: JSON.stringify(["Geografie", "Österreich"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welcher Baum verliert im Herbst seine Blätter?",
    choices: JSON.stringify(["Laubbaum", "Nadelbaum", "Palme", "Kaktus"]),
    answerIndex: 0,
    fact: "Nadelbäume behalten ihre Nadeln das ganze Jahr.",
    tags: JSON.stringify(["Natur", "Pflanzen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt der Schweiz?",
    choices: JSON.stringify(["Bern", "Zürich", "Genf", "Basel"]),
    answerIndex: 0,
    fact: "Bern ist seit 1848 Bundesstadt.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Tier kann fliegen und ist nachtaktiv?",
    choices: JSON.stringify(["Fledermaus", "Eule", "Schmetterling", "Biene"]),
    answerIndex: 0,
    fact: "Fledermäuse sind die einzigen Säugetiere, die fliegen können.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Wie viele Saiten hat eine Gitarre normalerweise?",
    choices: JSON.stringify(["6", "4", "8", "12"]),
    answerIndex: 0,
    fact: "Es gibt auch 12-saitige Gitarren.",
    tags: JSON.stringify(["Musik", "Instrumente"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welcher Monat ist der erste im Jahr?",
    choices: JSON.stringify(["Januar", "Februar", "Dezember", "März"]),
    answerIndex: 0,
    fact: "Januar ist nach dem römischen Gott Janus benannt.",
    tags: JSON.stringify(["Zeit", "Allgemeinwissen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier hat einen Rüssel?",
    choices: JSON.stringify(["Elefant", "Giraffe", "Löwe", "Zebra"]),
    answerIndex: 0,
    fact: "Der Rüssel eines Elefanten hat über 40.000 Muskeln.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von England?",
    choices: JSON.stringify(["London", "Manchester", "Liverpool", "Birmingham"]),
    answerIndex: 0,
    fact: "London ist eine der größten Städte Europas.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farbe entsteht, wenn man Rot und Weiß mischt?",
    choices: JSON.stringify(["Rosa", "Orange", "Lila", "Braun"]),
    answerIndex: 0,
    fact: "Rosa ist eine helle Variante von Rot.",
    tags: JSON.stringify(["Kunst", "Farben"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Seiten hat ein Würfel?",
    choices: JSON.stringify(["6", "4", "8", "12"]),
    answerIndex: 0,
    fact: "Jede Seite eines Würfels ist ein Quadrat.",
    tags: JSON.stringify(["Mathematik", "Geometrie"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier hat Streifen?",
    choices: JSON.stringify(["Zebra", "Löwe", "Elefant", "Giraffe"]),
    answerIndex: 0,
    fact: "Jedes Zebra hat ein einzigartiges Streifenmuster.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt der längste Fluss Europas?",
    choices: JSON.stringify(["Wolga", "Donau", "Rhein", "Elbe"]),
    answerIndex: 0,
    fact: "Die Wolga ist 3.530 km lang.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.HARD,
  },
  {
    prompt: "Welches Tier hat einen langen Hals?",
    choices: JSON.stringify(["Giraffe", "Elefant", "Löwe", "Zebra"]),
    answerIndex: 0,
    fact: "Giraffen sind die größten Landtiere.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Ecken hat ein Quadrat?",
    choices: JSON.stringify(["4", "3", "5", "6"]),
    answerIndex: 0,
    fact: "Alle Seiten eines Quadrats sind gleich lang.",
    tags: JSON.stringify(["Mathematik", "Geometrie"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farbe hat eine Banane?",
    choices: JSON.stringify(["Gelb", "Grün", "Rot", "Blau"]),
    answerIndex: 0,
    fact: "Unreife Bananen sind grün.",
    tags: JSON.stringify(["Natur", "Lebensmittel"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Griechenland?",
    choices: JSON.stringify(["Athen", "Sparta", "Thessaloniki", "Kreta"]),
    answerIndex: 0,
    fact: "Athen ist eine der ältesten Städte der Welt.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier kann im Wasser und an Land leben?",
    choices: JSON.stringify(["Frosch", "Fisch", "Vogel", "Hund"]),
    answerIndex: 0,
    fact: "Frösche sind Amphibien.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Jahreszeiten gibt es?",
    choices: JSON.stringify(["4", "3", "5", "2"]),
    answerIndex: 0,
    fact: "Frühling, Sommer, Herbst und Winter.",
    tags: JSON.stringify(["Natur", "Jahreszeiten"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welche Farbe hat Schnee?",
    choices: JSON.stringify(["Weiß", "Blau", "Grau", "Gelb"]),
    answerIndex: 0,
    fact: "Schnee besteht aus gefrorenen Wasserkristallen.",
    tags: JSON.stringify(["Natur", "Wetter"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Portugal?",
    choices: JSON.stringify(["Lissabon", "Porto", "Madrid", "Barcelona"]),
    answerIndex: 0,
    fact: "Lissabon liegt am Atlantik.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Tier gibt uns Honig?",
    choices: JSON.stringify(["Biene", "Wespe", "Hummel", "Schmetterling"]),
    answerIndex: 0,
    fact: "Bienen sammeln Nektar und machen daraus Honig.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Tage hat der Februar in einem Schaltjahr?",
    choices: JSON.stringify(["29", "28", "30", "31"]),
    answerIndex: 0,
    fact: "Schaltjahre gibt es alle 4 Jahre.",
    tags: JSON.stringify(["Zeit", "Kalender"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Tier hat einen Panzer?",
    choices: JSON.stringify(["Schildkröte", "Frosch", "Fisch", "Vogel"]),
    answerIndex: 0,
    fact: "Der Panzer schützt die Schildkröte.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Dänemark?",
    choices: JSON.stringify(["Kopenhagen", "Oslo", "Stockholm", "Helsinki"]),
    answerIndex: 0,
    fact: "Kopenhagen ist bekannt für die kleine Meerjungfrau.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welche Farbe hat eine Orange?",
    choices: JSON.stringify(["Orange", "Gelb", "Rot", "Grün"]),
    answerIndex: 0,
    fact: "Die Frucht und die Farbe haben den gleichen Namen.",
    tags: JSON.stringify(["Natur", "Lebensmittel"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Wochen hat ein Jahr ungefähr?",
    choices: JSON.stringify(["52", "48", "50", "54"]),
    answerIndex: 0,
    fact: "Genau sind es 52 Wochen und 1 Tag.",
    tags: JSON.stringify(["Zeit", "Kalender"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welches Tier kann sehr gut klettern?",
    choices: JSON.stringify(["Affe", "Hund", "Kuh", "Pferd"]),
    answerIndex: 0,
    fact: "Affen leben oft in Bäumen.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Schweden?",
    choices: JSON.stringify(["Stockholm", "Kopenhagen", "Oslo", "Helsinki"]),
    answerIndex: 0,
    fact: "Stockholm liegt auf 14 Inseln.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welche Farbe hat eine Karotte?",
    choices: JSON.stringify(["Orange", "Rot", "Gelb", "Grün"]),
    answerIndex: 0,
    fact: "Karotten sind gut für die Augen.",
    tags: JSON.stringify(["Natur", "Lebensmittel"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Minuten hat eine Stunde?",
    choices: JSON.stringify(["60", "50", "100", "30"]),
    answerIndex: 0,
    fact: "Eine Stunde hat 60 Minuten und 3600 Sekunden.",
    tags: JSON.stringify(["Zeit", "Mathematik"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier kann sehr schnell rennen?",
    choices: JSON.stringify(["Pferd", "Schildkröte", "Schnecke", "Igel"]),
    answerIndex: 0,
    fact: "Pferde können bis zu 70 km/h schnell laufen.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Norwegen?",
    choices: JSON.stringify(["Oslo", "Stockholm", "Kopenhagen", "Helsinki"]),
    answerIndex: 0,
    fact: "Oslo liegt am Oslofjord.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welche Farbe hat Gras?",
    choices: JSON.stringify(["Grün", "Gelb", "Braun", "Blau"]),
    answerIndex: 0,
    fact: "Gras ist grün wegen des Chlorophylls.",
    tags: JSON.stringify(["Natur", "Pflanzen"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie viele Sekunden hat eine Minute?",
    choices: JSON.stringify(["60", "50", "100", "30"]),
    answerIndex: 0,
    fact: "60 Sekunden = 1 Minute.",
    tags: JSON.stringify(["Zeit", "Mathematik"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Welches Tier kann fliegen und summen?",
    choices: JSON.stringify(["Biene", "Hund", "Katze", "Fisch"]),
    answerIndex: 0,
    fact: "Bienen können bis zu 30 km/h schnell fliegen.",
    tags: JSON.stringify(["Tiere", "Natur"]),
    difficulty: QuizDifficulty.EASY,
  },
  {
    prompt: "Wie heißt die Hauptstadt von Finnland?",
    choices: JSON.stringify(["Helsinki", "Oslo", "Stockholm", "Kopenhagen"]),
    answerIndex: 0,
    fact: "Helsinki ist die nördlichste Hauptstadt der EU.",
    tags: JSON.stringify(["Geografie", "Europa"]),
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    prompt: "Welche Farbe hat Feuer?",
    choices: JSON.stringify(["Rot/Orange", "Blau", "Grün", "Schwarz"]),
    answerIndex: 0,
    fact: "Sehr heißes Feuer kann auch blau sein.",
    tags: JSON.stringify(["Natur", "Physik"]),
    difficulty: QuizDifficulty.EASY,
  },
];

async function main() {
  console.log('🌱 Seeding database...');
  
  // Clear existing data
  await prisma.quizQuestion.deleteMany();
  await prisma.session.deleteMany();
  
  console.log('✨ Creating quiz questions...');
  
  for (const question of questions) {
    await prisma.quizQuestion.create({
      data: question,
    });
  }
  
  console.log(`✅ Created ${questions.length} quiz questions`);
  console.log('🎉 Seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

